### ISSUE TITLE
kubernetes-NGINX Ingress Controller

### ISSUE THREAD

**Issue by BurlyLuo** [thenativeweb/wolkenkit-eventstore#14]
Hello Jan-Hendrik
About your passage :https://www.thenativeweb.io/blog/2018-07-03-16-17-kubernetes-using-ingress-with-ssl-tls-termination-and-http2/
which aims at http2 .
But  There are many troubles about the controller.
First:The pod  ingress-controller-helm-nginx-ingress-controller-default-b5kspq   0/1     CrashLoopBackOff   6          10m    10.244.1.60   k8s-2   <none>           <none>
Second:If I add annotations    
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
to enable http2.But pod of nginx may not be proxy to the backend service.So , I can not access to the backend pods.
But if I remove the annotations    .It is OK!
Please Help Me solve this problems.Many thanks for you.

**Comment by goloroden** [comment]
@BurlyLuo Thanks for bringing up this question, but unfortunately we don't provide support on blog posts.  Since your question is also not related to this module / repository, I'm going to close this issue.

If you need professional support, please contact us via [email](hello@thenativeweb.io).
Alternatively, you could ask on [StackOverflow](https://stackoverflow.com/).
