### ISSUE TITLE
Dependency referenced by hash

### ISSUE THREAD

**Issue by lorenzleutgeb** [thenativeweb/wolkenkit-eventstore#19]
Hi! I'd like to ask that you do not depend on other packages by Git hash. Thank you.

https://github.com/thenativeweb/wolkenkit-eventstore/blob/0c03d7cf2ee852acf46ed3b1a9a3dbee559c6246/package.json#L42

**Comment by goloroden** [comment]
Thanks for bringing up this issue.

Depending on a specific Git hash is actually not the best idea, but in this case it was needed.

Does this cause any specific problems in your case?

**Comment by lorenzleutgeb** [comment]
Yes, this dependency cannot be downloaded by tools that don't support referencing GitHub repositories. It is *much* more common to just use the global NPM registry.

**Comment by goloroden** [comment]
This change was done as part of a larger one, and probably the new version had been published accidentally (I can only guess here, since this was four months ago, and TBH I don't remember the exact situation any more).

However, your best option is probably to step back to 2.6.0, which neither contains the breaking change that caused issues nor the reference to GitHub.

This should fix the issue then.

**Comment by lorenzleutgeb** [comment]
Right, but this proposal leaves me stuck at 2.6.0. My idea was to ask for *future* versions to avoid hashes.

**Comment by goloroden** [comment]
Ah, okay… but yes, in future versions we will avoid this (respectively don't do this any more).
