### ISSUE TITLE
Do something about events with an out-of-range revision 

### ISSUE THREAD

**Issue by lorenzleutgeb** [thenativeweb/wolkenkit-eventstore#7]
I am using the PostgreSQL implementation, but I think that other implementations might be affected as well.

The **issue** is that `wolkenkit-eventstore/postgres` happily saves an event with `event.metadata.revision == 0`. However, the [default `fromRevision` is 1](https://github.com/thenativeweb/wolkenkit-eventstore/blob/master/src/postgres/Eventstore.js#L126) which is in obvious ways greater than 0.

The **observed behaviour** is that events being saved to the DB are not read later on, and it is not obvious why that is so. You will see the event in your DB, but `getEventStream` will return nothing. Also, there are no errors being thrown.

The **misunderstanding** is that I thought zero is fine as the "first" version (we all start counting at zero, don't we?) and ran into trouble because I could not read out my events with default parameters!

Proposed actions:
 1. Since you are iterating over all events [in `saveEvents`](https://github.com/thenativeweb/wolkenkit-eventstore/blob/master/src/postgres/Eventstore.js#L246-L252) you might do a bounds check  there.
 2. You might want to enforce a revision greater than zero in the [`Event` constructor](https://github.com/thenativeweb/commands-events/blob/master/src/Event.js#L72-L96)
 3. If this is desired behaviour, please document it in `README.md` of this repository. You have a section on reading the last event, so maybe you can also add a few words on the range of revisions and the *first* event.

**Comment by susannaroden** [comment]
Hi there! Thank you so much for bringing this up and the detailed explainations! As soon as possible, we'll fix it!

**Comment by goloroden** [comment]
Hi @lorenzleutgeb 😊 

As @susannaroden already said, thanks for bringing up this issue, and thanks as well for the detailed analysis of the underlying problem. I'm very sorry for the problems you were facing, and we'll address them soon.

Unfortunately, we can't (right now) go with option 2, since having the `metadata.revision` property is optional, and not enforced at all by the constructor.

But, of course having the `saveEvents` function check the validity of the field is easy, and updating the documentation as well. Hence I think we'll do that 😊
